In [ ]:
import torch
from torch import nn
from torch.nn.utils.rnn import pad_sequence,pad_packed_sequence,pack_padded_sequence

In [ ]:
docs = ['cCcc1', 
        'NNccC1',
        'CNcN2',
        'ccN3']

In [ ]:
word_set=set()
for seq in docs:
  for word in list(seq):
    word_set.add(word)

word_list=['<pad>']+list(word_set)
print(word_list)

['<pad>', '3', 'N', 'c', '1', 'C', '2']


In [ ]:
word2idx={word: idx for idx,word in enumerate(word_list)}

vocab_size=len(word_list)
embedding_dim=10

In [ ]:
x=[torch.LongTensor([word2idx[word]for word in list(seq)])for seq in docs]
x_padded = pad_sequence(x, batch_first=True, padding_value=0)

print(x_padded)

tensor([[3, 5, 3, 3, 4, 0],
        [2, 2, 3, 3, 5, 4],
        [5, 2, 3, 2, 6, 0],
        [3, 3, 2, 1, 0, 0]])


In [ ]:
seq_len=torch.LongTensor(list(map(len,x)))
print(seq_len)

tensor([5, 6, 5, 4])


In [ ]:
embed=nn.Embedding(vocab_size,embedding_dim)
lstm=nn.LSTM(embedding_dim,hidden_size=5,batch_first=True)

In [ ]:
embedding_seq_tensor=embed(x_padded)
print(embedding_seq_tensor)

tensor([[[-2.2528,  1.2505,  1.2433,  0.1408, -1.2954, -0.2907,  0.4122,
          -1.6750,  1.5804,  1.5785],
         [ 1.1010,  0.9459, -0.4959, -1.2637, -0.6089, -0.1111,  0.7356,
           1.2366,  1.7242, -0.1740],
         [-2.2528,  1.2505,  1.2433,  0.1408, -1.2954, -0.2907,  0.4122,
          -1.6750,  1.5804,  1.5785],
         [-2.2528,  1.2505,  1.2433,  0.1408, -1.2954, -0.2907,  0.4122,
          -1.6750,  1.5804,  1.5785],
         [-1.5767, -0.7968,  0.5152,  0.1527,  0.3222, -0.3740, -0.1290,
          -1.6324, -0.0990,  0.2662],
         [-0.8084, -0.9533,  0.4109, -0.7779, -2.1192,  2.0858, -0.8745,
          -0.5976, -1.3992,  1.6567]],

        [[ 0.2103, -1.4328,  1.5144,  1.7459,  1.4352,  0.4651, -0.7167,
           0.9513, -0.7678, -1.1378],
         [ 0.2103, -1.4328,  1.5144,  1.7459,  1.4352,  0.4651, -0.7167,
           0.9513, -0.7678, -1.1378],
         [-2.2528,  1.2505,  1.2433,  0.1408, -1.2954, -0.2907,  0.4122,
          -1.6750,  1.5804,  1.5785],

In [ ]:
packed_input = pack_padded_sequence(embedding_seq_tensor, seq_len.cpu().numpy(), batch_first=True,enforce_sorted=False)
print(packed_input.data.shape)


torch.Size([4, 10])


In [ ]:

packed_output,(ht,ct)=lstm(packed_input)

packed_output.data.shape


torch.Size([4, 5])

In [ ]:
output, input_sizes = pad_packed_sequence(packed_output, batch_first=True)
print(ht[-1])

tensor([[-0.2994,  0.0059, -0.3161, -0.2518,  0.1614],
        [-0.2178,  0.0888, -0.1436,  0.0371, -0.3405],
        [-0.2344, -0.0833, -0.2771, -0.4951,  0.1655],
        [-0.2388, -0.2054,  0.1413,  0.3970, -0.1029]],
       grad_fn=<SelectBackward0>)
